previewsEnabled: true
services:
  - type: web
    name: narratives
    region: oregon
    env: node
    plan: starter
    healthCheckPath: /
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: MONGO_DB
        value: narratives
        previewValue: image-rio-narratives
      - fromGroup: narratives
      - fromGroup: sendgrid
