previewsEnabled: true
services:
  - type: web
    name: narratives
    region: oregon
    env: node
    plan: starter
    healthCheckPath: /
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - fromGroup: narratives
      - key: MONGO_URI
        sync: false
